AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create EOD lambda function with sqs, dlq and i am role.
Parameters:
  EODSourceQueueName:
    Type: String
    Description: EOD standard queue name
  EODDeadLetterQueueName:
    Type: String
    Description: EOD deadletter Queue name
  EODIAMroleName:
    Type: String
    Description: EOD i am role name
  LambdaFunctionName:
    Type: String
    Description: Lambda function name.
Resources:
  EODSourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Ref: EODSourceQueueName
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - EODDeadLetterQueue
            - Arn
        maxReceiveCount: 2
  EODDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Ref: EODDeadLetterQueueName
  EODIAMrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: EODIAMroleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - glue.amazonaws.com
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: eodsqslambdaexecutionpolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - sqs:*
                  - ssm:*
                Resource: '*'
        - PolicyName: eodlambdacloudwatchexecutiontpolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
  eodsqslambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 
        Ref: LambdaFunctionName
      Handler: eod.lambda_handler
      Role:
        Fn::GetAtt:
          - EODIAMrole
          - Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            message = "Hello Lambda World!!!"
            return message
      Runtime: python3.7
      MemorySize: 128
      Timeout: 30
    DependsOn:
      - EODIAMrole
  lambdaSqs:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      EventSourceArn: arn:aws:sqs:us-east-2:470174335172:eod_sqs
      FunctionName:
        Ref: eodsqslambda