AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create Schedular lambda function with Schedular.
Parameters:
  SchedularIAMroleName:
    Type: String
    Description: EOD i am role name
  LambdaFunctionName:
    Type: String
    Description: Lambda function name.
Resources:
  SchedularIAMrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: SchedularIAMroleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - glue.amazonaws.com
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: eodsqslambdaexecutionpolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - sqs:*
                  - ssm:*
                Resource: '*'
        - PolicyName: eodlambdacloudwatchexecutiontpolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
  schedularlambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 
        Ref: LambdaFunctionName
      Handler: schedular.lambda_handler
      Role:
        Fn::GetAtt:
          - SchedularIAMrole
          - Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            message = "Hello Lambda World!!!"
            return message
      Runtime: python3.7
      MemorySize: 128
      Timeout: 30
    DependsOn:
      - SchedularIAMrole
  SchedularRule:
    Type: AWS::Events::Rule
    Properties:
      Description: A schedule for the Lambda function.
      ScheduleExpression: rate(10 minutes)
      Targets:
        - Id: rule_Scheduler
          Arn:
            Fn::GetAtt:
              - schedularlambda
              - Arn
  InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
          - schedularlambda
          - Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - SchedularRule
          - Arn