name: Create s3 bucket and lambda

on:
  # push:
  workflow_dispatch:
    branches:
      - master
jobs:
  create-s3Upload:
    name: create s3Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - run: aws cloudformation create-stack --stack-name stack-for-s3Upload --template-body file://src/main/templates/copying-resources/s3Upload.yaml
             --parameters ParameterKey=LambdaFunctionName,ParameterValue=file_parser
             ParameterKey=s3BucketName,ParameterValue=sftp-source-bucket --capabilities CAPABILITY_NAMED_IAM