name: Create Schedular Lambda

on:
  # push:
  workflow_dispatch:
    branches:
      - master
      - First_Branch
jobs:
  create-schedular-lambda:
    name: create schedular lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - run: aws cloudformation create-stack --stack-name stack-for-schedular-lambda --template-body file://scheduler.yaml
             --parameters ParameterKey=LambdaFunctionName,ParameterValue=Schedular_lambda 
             ParameterKey=SchedularIAMroleName,ParameterValue=SchedularRole --capabilities CAPABILITY_NAMED_IAM