name: Create price survey lambda 

on:
  # push:
  workflow_dispatch:
    branches:
      - master
jobs:
  create-pricesurvey-lambda:
    name: create pricesurvey lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - run: aws cloudformation create-stack --stack-name stack-for-pricesurvey-lambda --template-body file://Pricesurvey.yaml 
             --parameters ParameterKey=LambdaFunctionName,ParameterValue=priceSurvey_lambda
             ParameterKey=PriceSurveySourceQueueName,ParameterValue=priceSurvey_sqs
             ParameterKey=PriceSurveyDeadLetterQueueName,ParameterValue=priceSurvey_dlq
             ParameterKey=PriceSurveyIAMroleName,ParameterValue=priceSurveyrole --capabilities CAPABILITY_NAMED_IAM