name: Create params in parameter store

on:
  # push:
  workflow_dispatch:
    branches:
      - master
      - First_Branch
jobs:
  create-params:
    name: create params
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - run: aws cloudformation create-stack --stack-name stack-for-parameters --template-body file://Parameters.yaml --capabilities CAPABILITY_NAMED_IAM