name: Create Secrets Manager

on:
  # push:
  workflow_dispatch:
    branches:
      - main
      - dev
jobs:
  create-secrets-manager:
    name: create secrets manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2
          
      - run: aws cloudformation create-stack --stack-name PCI-secrets-manager-Stack1
              --template-body file://src/main/PCITemplates/PCICopyingServices/PCITemplateSecretsManager.yml
              --parameters ParameterKey=Vpc1,ParameterValue=vpc-04f134a8bbfb08772 
              ParameterKey=Subnets1,ParameterValue=\'subnet-0874a75a4edf38d10,subnet-0ad0a719fa2d2389d\'
              ParameterKey=FileServersCIDR1,ParameterValue=10.0.0.0/8  --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND