name: Delete Schedular Lambda

on:
  # push:
  workflow_dispatch:
    branches:
      - master
      - First_Branch
jobs:
  delete-schedular-lambda:
    name: delete schedular lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - run: aws cloudformation delete-stack --stack-name stack-for-schedular-lambda