name: Create SMB Stack

on:
  push:
    branches:
      - First_Branch
      - main
      - dev
      - master
  workflow_dispatch:
    branches:
      - main
      - dev
      - master
jobs:
  create-smb-stack:
    name: create smb stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - run: aws cloudformation create-stack --stack-name PCI-SMB-Stack --template-body file://template.yaml --capabilities CAPABILITY_AUTO_EXPAND #CAPABILITY_IAM