name: Update Eod Lambda

on:
  # push:
  workflow_dispatch:
    branches:
      - master
      - First_Branch
jobs:
  update-eod-lambda:
    name: update eod lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - run: zip -j eod-deployment-package.zip src/main/lambda/copying_service/eod.py src/main/lambda/copying_service/eod1.py
      - run: aws lambda update-function-code --function-name EOD_lambda --zip-file fileb://eod-deployment-package.zip

  # update-eod1-lambda:
  #   name: update eod1 lambda
  #   runs-on: ubuntu-latest
  #   needs: update-eod-lambda
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #     - uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-2

  #     - run: zip eod1-deployment-package.zip eod1.py
  #     - run: aws lambda update-function-code --function-name EOD_lambda --zip-file fileb://eod1-deployment-package.zip