name: Update price survey Lambda

on:
  # push:
  workflow_dispatch:
    branches:
      - master
      - First_Branch
jobs:
  update-eod-lambda:
    name: update eod lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - run: zip priceSurvey-deployment-package.zip priceSurvey.py #This generates a priceSurvey-deployment-package.zip file in your project directory.
      - run: aws lambda update-function-code --function-name priceSurvey_lambda --zip-file fileb://priceSurvey-deployment-package.zip